FROM httpd
MAINTAINER Bhargav
LABEL This is bill manager application. Containing Home Page and Managing Page.
EXPOSE 80
COPY home.html /usr/local/apache2/htdocs/
COPY index.html /usr/local/apache2/htdocs/

